/*
 * JSP generated by Resin-3.1.12 (built Mon, 29 Aug 2011 03:22:08 PDT)
 */

package _jsp._web_22dinf._jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _testprogress__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html;charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      _caucho_expr_0.print(out, _jsp_env, false);
      out.write(_jsp_string1, 0, _jsp_string1.length);
      _caucho_expr_0.print(out, _jsp_env, false);
      out.write(_jsp_string2, 0, _jsp_string2.length);
      _caucho_expr_0.print(out, _jsp_env, false);
      out.write(_jsp_string3, 0, _jsp_string3.length);
      _caucho_expr_0.print(out, _jsp_env, false);
      out.write(_jsp_string4, 0, _jsp_string4.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 7170261747151080670L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
    _caucho_expr_0 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${timestamp}");
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/jsp/testProgress.jsp"), 4395430620150638477L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }
  private static com.caucho.el.Expr _caucho_expr_0;

  private final static char []_jsp_string3;
  private final static char []_jsp_string2;
  private final static char []_jsp_string1;
  private final static char []_jsp_string0;
  private final static char []_jsp_string4;
  static {
    _jsp_string3 = "\"></script>\r\n<link rel=\"stylesheet\" href=\"http://rwww.picooapp.com/css/jquery-ui.css?ver=".toCharArray();
    _jsp_string2 = "\"></script>\r\n<script src=\"http://rwww.picooapp.com/js/jquery-ui.js?ver=".toCharArray();
    _jsp_string1 = "\">\r\n<script type=\"text/javascript\"\r\n        src=\"http://rwww.picooapp.com/js/jquery-1.11.3.min.js?ver=".toCharArray();
    _jsp_string0 = "\r\n\r\n<!DOCTYPE HTML>\r\n<html>\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\">\r\n<title>\u53d1\u9001\u90ae\u4ef6</title>\r\n<link rel=\"stylesheet\" href=\"css/email.css?ver=".toCharArray();
    _jsp_string4 = "\" />\r\n<style>\r\n\r\n    .ui-progressbar {\r\n        border: none;\r\n        background : #b0d0ef;\r\n        position: relative;\r\n        height: 5px;\r\n    }\r\n\r\n    .ui-progressbar-value{\r\n        background : #3d8bf2;\r\n    }\r\n</style>\r\n\r\n\r\n<script type=\"text/javascript\">\r\n$(function () {\r\n\r\n    $.ajaxSetup({cache: false });\r\n    var pro = $( \"#progressbar\" );   //\u8fdb\u5ea6\u6761div\r\n    pro.progressbar({\r\n        value: false   //\u521d\u59cb\u5316\u7684\u503c\u4e3a0\r\n\r\n    });\r\n    setTimeout( addValue, 500);\r\n\r\n    //\u52a8\u6001\u4fee\u6539value\u7684\u51fd\u6570\r\n    function addValue(){\r\n        var pro = $( \"#progressbar\" );\r\n        var newValue;\r\n        if(pro.progressbar(\"value\")>=0){ newValue = pro.progressbar(\"value\") +1;}\r\n\r\n\r\n        pro.progressbar(\"value\",newValue); //\u8bbe\u7f6e\u65b0\u503c\r\n        if( newValue >= 95) {return;}    //\u8d85\u8fc7100\u65f6\uff0c\u8fd4\u56de\r\n\r\n        setTimeout( addValue, 200); //\u5ef6\u8fdf20\u6beb\u79d2\u9012\u5f52\u8c03\u7528\u81ea\u5df1\r\n    }\r\n\r\n\r\n});\r\n\r\n//\u5ef6\u8fdf500\u6beb\u79d2\u8c03\u7528\u4fee\u6539value\u7684\u51fd\u6570\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n</script>\r\n\r\n</head>\r\n\r\n<body>\r\n\r\n\r\n    <div id=\"progressbar\" class=\"ui-progressbar\"></div>\r\n\r\n</body>\r\n</html>".toCharArray();
  }
}
